apiVersion: v1
kind: Secret
metadata:
  name: jenkins-docker-cfg
  namespace: default
data:
    .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJrOHMtZGVtby1yZWdpc3RyeS5jbi1zaGFuZ2hhaS5jci5hbGl5dW5jcy5jb20iOiB7CgkJCSJhdXRoIjogIlkyNTFNRGM0Ykd4QVlXMTNZWGxvZVdKeWFYTndiMk02UjJGMWMzTXhPVEE1IgoJCX0KCX0sCgkiSHR0cEhlYWRlcnMiOiB7CgkJIlVzZXItQWdlbnQiOiAiRG9ja2VyLUNsaWVudC8xOC4wOS4yIChsaW51eCkiCgl9Cn0=
type: kubernetes.io/dockerconfigjson